const Mobil = [
    {
      id: '1',
      title: 'Tesla 3',
      description: 'Tesla Model 3 is an electric car with a range of over 300 miles.',
      image: require('../assets/tesla3.jpg'),
      details: 'The Tesla Model 3 is a sleek, modern, and efficient all-electric car, equipped with autopilot technology, a large touch screen display, and a minimalist interior design.',
      type: 'Tesla',
      price: '$650 / 3 days',
      seat: '4',
      speed: '225 Km/Hours',
    },
    {
      id: '2',
      title: 'Tesla X',
      description: 'The Tesla Model X is an all-electric luxury SUV and impressive acceleration.',
      image: require('../assets/teslax.jpg'),
      details: `The Model X is known for its impressive acceleration, with some models capable of going from 0 to 60 mph in under 2.5 seconds.`,
      type: 'Tesla',
      price: '$700 / 3 days',
      seat: '4',
      speed: '250 Km/Hours',
    },
    {
      id: '3',
      title: 'Audi RS E-tron GT',
      description: 'The Audi RS e-tron GT is an all-electric high-performance luxury sedan.',
      image: require('../assets/audirs-etron-gt.jpg'),
      details: `The Audi RS e-tron GT is a high-performance all-electric sedan, featuring a sleek design, advanced technology, and powerful electric motors that deliver strong acceleration and a range of up to 238 miles per charge.`,
      type: 'Audi',
      price: '$750 / 3 days',
      seat: '4',
      speed: '245 Km/Hours',
    },
    {
      id: '4',
      title: 'Audi RS 7',
      description: 'The Audi RS7 is a high-performance luxury sedan with sporty styling and advanced technology.',
      image: require('../assets/audirs7.jpg'),
      details: `The Audi RS7 is a powerful, luxurious sports sedan featuring advanced technology and sleek styling.`,
      type: 'Audi',
      price: '$800 / 3 days',
      seat: '4',
      speed: '306 Km/Hours',
    },
    {
      id: '5',
      title: 'Mazda 3',
      description: 'The Mazda 3 is a compact car with sporty handling, fuel-efficient engine and stylish design.',
      image: require('../assets/mazda3.png'),
      details: `The Mazda 3 is a compact car that offers a balance of sporty handling, fuel-efficiency, and stylish design, with a range of options for the engines and trims, it also offers advanced safety features, comfort and technology.`,
      type: 'Mazda',
      price: '$850 / 3 days',
      seat: '4',
      speed: '199 Km/Hours',
    },
    {
      id: '6',
      title: 'Mazda MX 5',
      description: 'The Mazda MX-5, also known as the Miata, is a lightweight, and a fun-to-drive experience.',
      image: require('../assets/mazdamx5.png'),
      details: `The Mazda MX-5 (also known as the Miata) is a lightweight, two-seat roadster that offers a fun-to-drive experience, with agile handling, a choice of manual or automatic transmission and a range of engines options, it also features a comfortable and stylish interior, and it is considered as one of the most affordable sports car in the market.`,
      type: 'Mazda',
      price: '$900 / 3 days',
      seat: '2',
      speed: '194 Km/Hours',
    },
    {
      id: '7',
      title: 'BMW I4',
      description: 'The BMW i4 is an electric luxury sedan with sleek styling.',
      image: require('../assets/bmwi4.png'),
      details: `The BMW i4 is an all-electric luxury sedan that features sleek styling, advanced technology, and powerful performance, with a range of up to 373 miles on a single charge, it offers a comfortable and spacious interior, with a variety of advanced safety features, and it also offers a sporty driving experience with instant torque and smooth acceleration.`,
      type: 'BMW',
      price: '$950 / 3 days',
      seat: '4',
      speed: '190 Km/Hours',
    },
    {
      id: '8',
      title: 'BMW M8',
      description: 'The BMW M8 is a high-performance luxury coupe with sporty styling.',
      image: require('../assets/bmwm8.png'),
      details: `The BMW M8 is a high-performance luxury coupe that features sporty styling, advanced technology and a powerful engine, with a range of options between V8 and V12, it offers agile handling, a comfortable and luxurious interior, and a variety of advanced safety features, it also offers a variety of models like the M8 Competition, M8 Gran Coupe, M8 Convertible and M8 GTE which is a racing version of the car.`,
      type: 'BMW',
      price: '$1000 / 3 days',
      seat: '2',
      speed: '200 Km/Hours',
    },
  ];
  
  export default Mobil;